Add typing for non-string config
- add typing for `health_report_interval`
- add typing for `default_sleep_timeout`

Why?

Makes it so you can override the default via env vars. Config overridden
by env vars are `str`'s otherwise.

Fixes -

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/microcosm_daemon/state_machine.py", line 26, in step
    next_state = self.current_state(self.graph)
  File "/usr/local/lib/python3.9/site-packages/microcosm_daemon/sleep_policy.py", line 38, in __exit__
    self.sleep(value.sleep_timeout or self.default_sleep_timeout)
  File "/usr/local/lib/python3.9/site-packages/microcosm_daemon/sleep_policy.py", line 31, in sleep
    sleep(sleep_timeout)
TypeError: an integer is required (got type str)
```